# Generated by Django 5.1 on 2024-08-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('userName', models.CharField(blank=True, max_length=255, null=True)),
                ('userRating', models.IntegerField(blank=True, null=True)),
                ('userReview', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
