# Generated by Django 5.1 on 2024-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('plot', models.CharField(max_length=255)),
            ],
        ),
    ]
