# Generated by Django 5.1 on 2024-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='userRating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='plot',
            new_name='userReview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='movie',
            name='userName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
